# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
