# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20160907_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_date',
        ),
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
